version: '3'
services:
  postgres-server:
    image: postgres:13.0
    container_name: postgres
    build:
      context: .
      dockerfile: ./init_db/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

  flask:
    container_name: flask
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres-server
    ports:
      - 5000:5000
    tty: true
    environment:
      TZ: "Asia/Tokyo"
    env_file: .env