version: '3'
services:
  postgres-server:
    image: postgres:13.0
    container_name: postgres
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d

  flask:
    container_name: flask
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres-server
    ports:
      - 5000:5000
    volumes:
      - .:/app
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
      FLASK_APP: './src/main.py'
    # command: 'pip install -r ./requirements.txt'
    # command: >
    #   sh -c '
    #       pip install -r ./requirements.txt
    #       flask run --host 0.0.0.0 --port 5000
    #   '