version: '3'
services:
  postgres:
    image: postgres:13.0
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d

  flask:
    container_name: flask
    build:
      context: ../.
      dockerfile: ./dev/Dockerfile
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - ../app:/code
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
      FLASK_APP: './src/main.py'
    command: "flask run --host 0.0.0.0 --port 5000"