version: '3'
services:
  postgres-server:
    image: postgres:13.0
    container_name: postgres
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d

  flask:
    container_name: flask
    build:
      context: ../.
      dockerfile: ./dev/Dockerfile
    depends_on:
      - postgres-server
    ports:
      - 5000:5000
    volumes:
      - ../app:/app
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
      FLASK_APP: '/app/main.py'
    command: >
      sh -c '
          pip install -r /app/requirements.txt
          flask run --host 0.0.0.0 --port 5000
      '