"""empty message

Revision ID: 090eaf5710a5
Revises: fd59b8276482
Create Date: 2020-11-27 00:32:56.462223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090eaf5710a5'
down_revision = 'fd59b8276482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search', 'name_en')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
