"""empty message

Revision ID: 79e5a51fa617
Revises: e01805d270a0
Create Date: 2020-12-01 22:55:21.088251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e5a51fa617'
down_revision = 'e01805d270a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('digit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search', 'digit')
    # ### end Alembic commands ###
