"""empty message

Revision ID: 85722573a95f
Revises: b762916c35d6
Create Date: 2020-10-15 11:14:24.586334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85722573a95f'
down_revision = 'b762916c35d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('home', sa.Column('station_distance', sa.Integer(), nullable=False))
    op.add_column('home', sa.Column('structure', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home', 'structure')
    op.drop_column('home', 'station_distance')
    op.drop_column('home', 'age')
    # ### end Alembic commands ###
