"""empty message

Revision ID: b762916c35d6
Revises: 
Create Date: 2020-10-15 00:02:25.092575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b762916c35d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home', 'age')
    op.drop_column('home', 'structure')
    op.drop_column('home', 'station_distance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home', sa.Column('station_distance', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('home', sa.Column('structure', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('home', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
