"""empty message

Revision ID: bf3f785c95fa
Revises: 2151efb53059
Create Date: 2020-11-27 00:13:17.029346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3f785c95fa'
down_revision = '2151efb53059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search', 'name_en')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
