"""empty message

Revision ID: f78e892caf39
Revises: 090eaf5710a5
Create Date: 2020-11-27 00:39:54.827366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78e892caf39'
down_revision = '090eaf5710a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search', 'name_en')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
