"""empty message

Revision ID: fd59b8276482
Revises: bf3f785c95fa
Create Date: 2020-11-27 00:25:37.192059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd59b8276482'
down_revision = 'bf3f785c95fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search', 'name_en')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
